name: plasmabio-Mineure_UE3
# channels priority
# see https://bioconda.github.io/
# conda-forge has highest priority
channels:
  - defaults
  - bioconda
  - conda-forge
dependencies:
  # Jupyter dependencies
  - jupyterhub>=1.5,<2
  - jupyterlab>=3.2,<4
  - jupyter-resource-usage
  - jupyterlab-topbar
  - jupyterlab-topbar-text
  - jupyterlab-system-monitor
  - nodejs
  - pip
  - python>=3.8
  # Jupyter archive
  # https://github.com/jupyterlab-contrib/jupyter-archive
  - jupyter-archive
  # Bash environment
  - bash_kernel
  # R packages
  - r-irkernel
  - r-base>=4.1.0
  - r-tidyverse
  - r-rcpp
  - r-tidyverse
  - r-factominer
  - r-factoextra
  - r-dt
  - r-repr
  - pip:
    - matplotlib
